---
title: "Taller Analisis Exploratorio"
author: Juan Esteban Zuñiga Possu
output: pdf_document
date: "2025-11-16"
---

```{r}
library(readxl)
datos<- read_excel(path = "bd2S.xlsx")

```

```{r setup, include=FALSE}
library(dplyr)
datos<- dplyr::mutate(datos,
    sexo = factor(sexo, levels = c(1, 2), labels = c("Masculino", "Femenino")),
    est_civ = factor(est_civ, levels = 1:5,
    labels = c("Soltero", "Casado", "Unión libre", "Separado", "Viudo")),
    educ = factor(educ, levels = 1:7,
    labels = c("Primaria", "Secundaria incompleta", "Secundaria completa",
                                  "Técnico", "Tecnológico", "Profesional", "Postgrado")),
    desemp = factor(desemp, levels = c(1, 2), labels = c("Sí", "No")),
    des_est = factor(des_est, levels = c(1, 2), labels = c("Sí", "No")),
    eps = factor(eps, levels = c(1, 2), labels = c("Sí", "No"))
  )
```



# Punto 1
## Punto 1

```{r}
library(ggplot2)
ggplot(datos, aes(x = tiemp_des)) +
  geom_histogram(binwidth = 2, boundary = 0, closed = "left") +
  geom_vline(xintercept = 12, linetype = "dashed") +
  labs(
    title = "Histograma del tiempo desempleado",
    x = "Tiempo desempleado (meses)",  # ajusta la unidad real
    y = "Frecuencia"
  )

# Porcentaje < 12 meses
prop_menor_1a <- mean(datos$tiemp_des < 12, na.rm = TRUE)
prop_menor_1a
```






```{r cars}
summary(datos)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
```{r}

```


